# PXA Platform Support
snd-soc-pxa2xx-objs := pxa2xx-pcm.o
snd-soc-pxa2xx-ac97-objs := pxa2xx-ac97.o
snd-soc-pxa2xx-i2s-objs := pxa2xx-i2s.o
snd-soc-pxa3xx-objs := pxa3xx-pcm.o
snd-soc-pxa3xx-ssp-objs := pxa3xx-ssp.o
snd-soc-pxa910-objs := pxa910-squ.o

obj-$(CONFIG_SND_PXA2XX_SOC) += snd-soc-pxa2xx.o
obj-$(CONFIG_SND_PXA2XX_SOC_AC97) += snd-soc-pxa2xx-ac97.o
obj-$(CONFIG_SND_PXA2XX_SOC_I2S) += snd-soc-pxa2xx-i2s.o
obj-$(CONFIG_SND_PXA3XX_SOC) += snd-soc-pxa3xx.o
obj-$(CONFIG_SND_PXA3XX_SOC_SSP) += snd-soc-pxa3xx-ssp.o
obj-$(CONFIG_SND_PXA910_SOC) += snd-soc-pxa910.o

# PXA Machine Support
snd-soc-corgi-objs := corgi.o
snd-soc-poodle-objs := poodle.o
snd-soc-tosa-objs := tosa.o
snd-soc-e800-objs := e800_wm9712.o
snd-soc-spitz-objs := spitz.o
snd-soc-em-x270-objs := em-x270.o
snd-soc-zylonite2-objs := zylonite2.o
snd-soc-aspenite-objs := aspenite.o
snd-soc-silvermoon-objs := silvermoon_wm8961.o
snd-soc-ttc-dkb-objs := ttc-dkb.o
snd-soc-tavorevb-objs := tavorevb.o
snd-soc-teton_bga-objs := teton_bga.o

obj-$(CONFIG_SND_PXA2XX_SOC_CORGI) += snd-soc-corgi.o
obj-$(CONFIG_SND_PXA2XX_SOC_POODLE) += snd-soc-poodle.o
obj-$(CONFIG_SND_PXA2XX_SOC_TOSA) += snd-soc-tosa.o
obj-$(CONFIG_SND_PXA2XX_SOC_E800) += snd-soc-e800.o
obj-$(CONFIG_SND_PXA2XX_SOC_SPITZ) += snd-soc-spitz.o
obj-$(CONFIG_SND_PXA2XX_SOC_EM_X270) += snd-soc-em-x270.o
obj-$(CONFIG_SND_PXA3XX_SOC_ZYLONITE2) += snd-soc-zylonite2.o
obj-$(CONFIG_SND_PXA3XX_SOC_ASPENITE) += snd-soc-aspenite.o
obj-$(CONFIG_SND_PXA3XX_SOC_SILVERMOON) += snd-soc-silvermoon.o
obj-$(CONFIG_SND_PXA910_SOC_TTC_DKB) += snd-soc-ttc-dkb.o
obj-$(CONFIG_SND_PXA910_SOC_TAVOREVB) += snd-soc-tavorevb.o
obj-$(CONFIG_SND_PXA3XX_SOC_TETON_BGA) += snd-soc-teton_bga.o
